package tools.dscode.common.annotations;

public enum DefinitionFlag {
    IGNORE_CHILDREN_IF_FALSE,
    DEBUG_LOGGING,
    _DEBUG_LOGGING,
    RUN_METHOD_DIRECTLY,
    _RUN_METHOD_DIRECTLY,
    IGNORE_CHILDREN,
    _IGNORE_CHILDREN,
    BLOCK_CONDITIONAL,
    NO_STEP_TEXT_RESOLUTION,
    NO_ARG_RESOLUTION,
    NO_RESOLUTION

}
