package tools.dscode.common.annotations;

public enum Phase {
    BEFORE_CUCUMBER_RUN,
    AFTER_CUCUMBER_RUN,
    BEFORE_SCENARIO_RUN,
    AFTER_SCENARIO_RUN,
    AFTER_SCENARIO_CLEANUP,
    AFTER_SCENARIO_FAIL,
    AFTER_SCENARIO_PASS,
    BEFORE_DOM_LOAD_CHECK,
    BEFORE_DOM_INTERACTION,
    AFTER_DOM_INTERACTION,
}