#!/usr/bin/env python3
"""Generate a deterministic repository inventory for coding agents."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "agent" / "repository-index.md"
GENERATED_GUIDANCE_PREFIX = "src/main/resources/META-INF/pickleball/guidance/"

EXCLUDED_PARTS = {
    ".agent-work",
    ".git",
    ".gradle",
    ".idea",
    "build",
    "target",
    "out",
    "node_modules",
    "__pycache__",
}
GROUPS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("Top-level project files", (
        "README.md",
        "build.gradle",
        "settings.gradle",
        "gradle.properties",
        "gradlew",
        "gradlew.bat",
        "maven-consumer-project/AGENTS.md",
        "maven-consumer-project/pom.xml",
        "maven-consumer-project/README.md",
        "maven-consumer-project/mvnw",
        "maven-consumer-project/mvnw.cmd",
        "maven-consumer-project/.mvn/wrapper/maven-wrapper.properties",
    )),
    ("Documentation", ("docs/**/*.md",)),
    ("Framework Java and AspectJ source", (
        "src/main/java/**/*.java",
        "src/main/aspectj/**/*",
        "src/main/resources/**/*",
    )),
    ("Framework tests", (
        "src/test/**/*.java",
        "src/test/**/*.feature",
        "src/test/resources/**/*",
    )),
    ("Control API module", (
        "pickleball-control-api/build.gradle",
        "pickleball-control-api/src/main/**/*",
        "pickleball-control-api/src/test/**/*",
    )),
    ("Maven consumer Java support", (
        "maven-consumer-project/src/test/java/**/*.java",
    )),
    ("Maven consumer feature scenarios", (
        "maven-consumer-project/src/test/resources/features/**/*.feature",
    )),
    ("Maven consumer service-call definitions", (
        "maven-consumer-project/src/test/resources/calls/**/*",
    )),
    ("Maven consumer configuration and data", (
        "maven-consumer-project/src/test/resources/configs/**/*",
        "maven-consumer-project/src/test/resources/data/**/*",
        "maven-consumer-project/src/test/resources/**/*.properties",
        "maven-consumer-project/src/test/resources/**/*.yml",
        "maven-consumer-project/src/test/resources/**/*.yaml",
        "maven-consumer-project/src/test/resources/**/*.json",
        "maven-consumer-project/src/test/resources/**/*.xml",
    )),
    ("Maven consumer test site", (
        "maven-consumer-project/src/test/resources/site/**/*",
    )),
    ("Agent contract and automation", (
        "AGENTS.md",
        "CLAUDE.md",
        "GEMINI.md",
        "REVIEW.md",
        ".aiassistant/rules/**/*",
        ".junie/**/*",
        ".github/copilot-instructions.md",
        ".github/agents/**/*",
        ".github/instructions/**/*",
        ".github/skills/**/*",
        ".amazonq/rules/**/*",
        ".agents/skills/**/*",
        ".claude/skills/**/*",
        ".cursor/rules/**/*",
        ".cursor/skills/**/*",
        ".continue/rules/**/*",
        ".clinerules/**/*",
        ".windsurf/rules/**/*",
        ".windsurf/skills/**/*",
        "scripts/agent_validate.*",
        "scripts/verify_agent_contract.py",
        "scripts/refresh_agent_index.py",
        "scripts/sync_consumer_guidance.py",
    )),
)


def is_included(path: Path) -> bool:
    if not path.is_file():
        return False
    relative = path.relative_to(ROOT)
    relative_text = relative.as_posix()
    if relative_text.startswith(GENERATED_GUIDANCE_PREFIX):
        return False
    return not any(part in EXCLUDED_PARTS for part in relative.parts)


def collect(patterns: tuple[str, ...]) -> list[str]:
    found: set[str] = set()
    for pattern in patterns:
        for path in ROOT.glob(pattern):
            if is_included(path):
                found.add(path.relative_to(ROOT).as_posix())
    return sorted(found, key=lambda value: (value.lower(), value))


def render() -> str:
    lines = [
        "# Pickleball Repository Index",
        "",
        "Generated by `scripts/refresh_agent_index.py`. Do not hand-edit.",
        "",
        "This inventory helps coding agents discover relevant files. It does not replace source inspection or `docs/agent/feature-map.md`.",
        "",
    ]
    for title, patterns in GROUPS:
        paths = collect(patterns)
        lines.extend((f"## {title}", ""))
        if paths:
            lines.extend(f"- `{path}`" for path in paths)
        else:
            lines.append("- _No matching files found._")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the generated index differs from the checked-in file.",
    )
    args = parser.parse_args()

    content = render()
    if args.check:
        if not OUTPUT.exists():
            print(f"ERROR: Missing {OUTPUT.relative_to(ROOT)}", file=sys.stderr)
            return 1
        current = OUTPUT.read_text(encoding="utf-8")
        if current != content:
            print(
                "ERROR: docs/agent/repository-index.md is stale. "
                "Run: python scripts/refresh_agent_index.py",
                file=sys.stderr,
            )
            return 1
        print("Repository index is current.")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8", newline="\n")
    print(f"Updated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
